[package]
name = "diesel-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.7", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15.7"


[[bin]]
name = "write_post"
path = "src/write_post"

